/**
 * The CSV round-trip is the M4 acceptance test: 60 nurses in, exported, re-imported, and
 * nothing changes. Also pins the two import behaviours that would cause real damage if they
 * regressed — duplicating nurses on re-import, and removing people who are not in the file.
 */

import {
  formatRosterCsv,
  isoDate,
  parseRosterCsv,
  ROSTER_COLUMNS,
  type RosterCsvRow,
  serializeCsv,
} from '@shiftnurse/core';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { auditHistoryFor } from '../audit.js';
import { type OpenedDatabase, openTestDatabase, transact } from '../client.js';
import { createUnit } from './config.js';
import {
  createNurse,
  getNurseByEmployeeId,
  listActiveNursesForUnit,
  listCredentials,
  listNurseCredentials,
} from './roster.js';
import { createCredential, exportRoster, importRoster } from './roster-io.js';

const ACTOR = 'manager';
let handle: OpenedDatabase;
let unitId: string;

beforeEach(() => {
  handle = openTestDatabase();
  unitId = createUnit(
    handle.db,
    {
      name: '4 West',
      unitType: 'Medical-Surgical',
      payPeriodDays: 14,
      payPeriodAnchor: isoDate('2026-01-04'),
    },
    ACTOR,
  ).id;
});
afterEach(() => handle.close());

/** 60 distinct nurses with a spread of roles, FTEs and credentials, generated by formula. */
function sixtyNurses(): string {
  const roles = ['RN', 'RN', 'RN', 'LPN', 'CNA'] as const;
  const types = ['full_time', 'part_time', 'per_diem', 'full_time'] as const;
  const rows: string[][] = [];
  for (let i = 0; i < 60; i++) {
    const fte = [1, 0.9, 0.6, 0.5][i % 4]!;
    rows.push([
      `E${1000 + i}`,
      `First${i}`,
      i % 7 === 0 ? `Last, ${i}` : `Last${i}`,
      roles[i % roles.length]!,
      types[i % types.length]!,
      String(fte),
      String(fte * 80),
      `20${String(10 + (i % 15)).padStart(2, '0')}-0${1 + (i % 9)}-15`,
      i % 5 === 0 ? 'yes' : 'no',
      i % 11 === 0 ? 'yes' : 'no',
      'yes',
      `555-01${String(i).padStart(2, '0')}`,
      `n${i}@unit.org`,
      i % 13 === 0 ? 'Note "quoted"' : '',
      i % 3 === 0 ? 'BLS:2027-06-30;ACLS:2026-12-31' : 'BLS:2027-06-30',
    ]);
  }
  return serializeCsv([ROSTER_COLUMNS, ...rows]);
}

describe('roster round trip', () => {
  it('imports 60 nurses from CSV, exports them, and re-imports the export unchanged', () => {
    const parsed = parseRosterCsv(sixtyNurses(), { payPeriodDays: 14 });
    expect(parsed.errors).toEqual([]);
    expect(parsed.rows).toHaveLength(60);

    const first = transact(handle.db, (tx) => importRoster(tx, unitId, parsed.rows, ACTOR));
    expect(first).toMatchObject({ created: 60, updated: 0, credentialsCreated: ['BLS', 'ACLS'] });
    expect(first.credentialsGranted).toBe(60 + 20);
    expect(listActiveNursesForUnit(handle.db, unitId)).toHaveLength(60);

    const exported = exportRoster(handle.db, unitId);
    expect(exported).toHaveLength(60);
    const text = formatRosterCsv(exported);
    const reparsed = parseRosterCsv(text, { payPeriodDays: 14 });
    expect(reparsed.errors).toEqual([]);
    expect(reparsed.rows).toEqual(exported);

    const second = transact(handle.db, (tx) => importRoster(tx, unitId, reparsed.rows, ACTOR));
    expect(second).toEqual({
      created: 0,
      updated: 60,
      credentialsCreated: [],
      credentialsGranted: 0,
      credentialsUpdated: 0,
    });
    expect(listActiveNursesForUnit(handle.db, unitId)).toHaveLength(60);
  });

  it('exports the awkward values faithfully — a comma in a surname and a quote in a note', () => {
    const parsed = parseRosterCsv(sixtyNurses(), { payPeriodDays: 14 });
    importRoster(handle.db, unitId, parsed.rows, ACTOR);
    const nurse = exportRoster(handle.db, unitId).find((r) => r.nurse.employeeId === 'E1000')!;
    expect(nurse.nurse.lastName).toBe('Last, 0');
    expect(nurse.nurse.notes).toBe('Note "quoted"');
  });
});

describe('roster import reconciliation', () => {
  const ada: RosterCsvRow = {
    nurse: {
      employeeId: 'E1',
      firstName: 'Ada',
      lastName: 'Okafor',
      role: 'RN',
      employmentType: 'full_time',
      fte: 1,
      contractedHoursPerPeriod: 80,
      seniorityDate: isoDate('2015-03-02'),
      isChargeEligible: true,
      isNovice: false,
      isFloatEligible: true,
      phone: '555-0100',
      email: undefined,
      notes: undefined,
    },
    credentials: [{ code: 'ACLS', expiresOn: isoDate('2027-03-01') }],
  };

  it('updates an existing nurse by employee id instead of creating a twin', () => {
    importRoster(handle.db, unitId, [ada], ACTOR);
    const changed = { ...ada, nurse: { ...ada.nurse, fte: 0.6, contractedHoursPerPeriod: 48 } };
    const summary = importRoster(handle.db, unitId, [changed], ACTOR);
    expect(summary).toMatchObject({ created: 0, updated: 1 });
    const nurses = listActiveNursesForUnit(handle.db, unitId);
    expect(nurses).toHaveLength(1);
    expect(nurses[0]!.fte).toBe(0.6);
  });

  it('leaves nurses who are not in the file untouched', () => {
    createNurse(
      handle.db,
      { ...ada.nurse, employeeId: 'E9', firstName: 'Bo', unitId, active: true },
      ACTOR,
    );
    importRoster(handle.db, unitId, [ada], ACTOR);
    expect(
      listActiveNursesForUnit(handle.db, unitId)
        .map((n) => n.employeeId)
        .sort(),
    ).toEqual(['E1', 'E9']);
  });

  it('reactivates a deactivated nurse who reappears in the file', () => {
    const created = createNurse(handle.db, { ...ada.nurse, unitId, active: false }, ACTOR);
    importRoster(handle.db, unitId, [ada], ACTOR);
    expect(listActiveNursesForUnit(handle.db, unitId).map((n) => n.id)).toEqual([created.id]);
  });

  it('reuses an existing credential by code and only creates unknown ones', () => {
    createCredential(
      handle.db,
      { code: 'ACLS', name: 'Advanced Cardiac Life Support', tracksExpiry: true },
      ACTOR,
    );
    const summary = importRoster(
      handle.db,
      unitId,
      [{ ...ada, credentials: [...ada.credentials, { code: 'PALS', expiresOn: undefined }] }],
      ACTOR,
    );
    expect(summary.credentialsCreated).toEqual(['PALS']);
    expect(
      listCredentials(handle.db)
        .map((c) => c.code)
        .sort(),
    ).toEqual(['ACLS', 'PALS']);
    const nurse = getNurseByEmployeeId(handle.db, unitId, 'E1')!;
    expect(listNurseCredentials(handle.db, nurse.id)).toHaveLength(2);
  });

  it('updates an expiry that moved and never revokes a credential missing from the file', () => {
    importRoster(handle.db, unitId, [ada], ACTOR);
    const nurse = getNurseByEmployeeId(handle.db, unitId, 'E1')!;
    const renewed = importRoster(
      handle.db,
      unitId,
      [{ ...ada, credentials: [{ code: 'ACLS', expiresOn: isoDate('2029-03-01') }] }],
      ACTOR,
    );
    expect(renewed).toMatchObject({ credentialsUpdated: 1, credentialsGranted: 0 });
    const stripped = importRoster(handle.db, unitId, [{ ...ada, credentials: [] }], ACTOR);
    expect(stripped).toMatchObject({ credentialsUpdated: 0, credentialsGranted: 0 });
    const held = listNurseCredentials(handle.db, nurse.id);
    expect(held).toHaveLength(1);
    expect(held[0]!.expiresOn).toBe('2029-03-01');
  });

  it('writes an audit trail: a create on first import, an update with before/after on the second', () => {
    importRoster(handle.db, unitId, [ada], ACTOR);
    const nurse = getNurseByEmployeeId(handle.db, unitId, 'E1')!;
    importRoster(
      handle.db,
      unitId,
      [{ ...ada, nurse: { ...ada.nurse, phone: '555-0199' } }],
      ACTOR,
    );
    const history = auditHistoryFor(handle.db, 'nurse', nurse.id);
    expect(history.map((h) => h.action)).toEqual(['update', 'create']);
    expect(history[0]!.before).toMatchObject({ phone: '555-0100' });
    expect(history[0]!.after).toMatchObject({ phone: '555-0199' });
  });
});
